
spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/inventorydb
        username: postgres
        password: Falconer

        # removing h2
        #url: jdbc:h2:mem:moviesdb
        #username: sa
        #password:
        #driver-class-name: org.h2.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    output:
        ansi:
            enabled: ALWAYS

server:
    port: 8282